name: Show Last Commit Info

on:
  push:
    branches:
      - main  # Trigger workflow on push events to the main branch
  workflow_dispatch:

jobs:
        show_commit_info:
          runs-on: ubuntu-latest
      
          steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            
            - name: Show Last Commit Info
              run: |
                git log -1 --pretty=format:"Last commit by %an on %cd: %s" --date=local
            
            - name: Calculate Time Difference
              id: time_diff
              run: |
                LAST_COMMIT_DATE=$(git log -1 --format=%at)
                CURRENT_DATE=$(date +%s)
                TIME_DIFF=$((CURRENT_DATE - LAST_COMMIT_DATE))
                echo "Time difference since last commit: $TIME_DIFF seconds"
      
            - name: Send Email if Time Difference > 1 minute
              
              run: |
                  echo "Sending email notification..."
                  echo "There have been no commits in the last 1 minute." | mail -s "No Commits in Last Minute" sharmanivesh08@gmail.com