name: Show Last Commit Info

on:
  push:
    branches:
      - main  # Trigger workflow on push events to the main branch

jobs:
  show_commit_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Show Last Commit Info
        run: |
          git log -1 --pretty=format:"Last commit by %an on %cd: %s" --date=local
